trigger:
- master

pool:
  name: Azure Pipelines
  demands: npm

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: 'InstaViajes_frontend'
    verbose: false

- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: custom
    workingDir: 'InstaViajes_frontend'
    verbose: false
    customCommand: 'run build'

- task: Docker@2
  displayName: 'Build and push Docker Image'
  inputs:
    containerRegistry: instadockersRegistry
    repository: 'instaviajes-frontend'
    Dockerfile: 'dockers/frontend/production_deploy/Dockerfile'

- task: SSH@0
  displayName: 'Pull docker images and runs it'
  inputs:
    sshEndpoint: 'Instaviajes Dockers SSH Service Connection'
    commands: |
     docker login instadockersregistry.azurecr.io
     
